import { NextResponse } from "next/server";
import { getAllCounts, getVotesFor, vote } from "@/lib/reactions";
import { clientIp, rateLimit } from "@/lib/rateLimit";
import { getTrip } from "@/lib/trips";

// Reads and writes reader data on every call — never prerender or cache it.
export const dynamic = "force-dynamic";

/** All counts, plus this reader's own picks when they identify themselves. */
export async function GET(request: Request) {
  const url = new URL(request.url);
  const voterId = url.searchParams.get("voter");
  // The ref is `<username>/<tripId>`, so a reaction can never be recorded
  // against another user's trip by guessing an id.
  const tripId = url.searchParams.get("trip");
  if (!tripId || !getTrip(tripId)) {
    return NextResponse.json({ error: "unknown_trip" }, { status: 400 });
  }
  const [counts, mine] = await Promise.all([
    getAllCounts(tripId),
    voterId ? getVotesFor(voterId, tripId) : Promise.resolve({}),
  ]);
  return NextResponse.json(
    { counts, mine },
    { headers: { "cache-control": "no-store" } },
  );
}

export async function POST(request: Request) {
  const limit = rateLimit(clientIp(request));
  if (!limit.ok) {
    return NextResponse.json(
      { error: "rate_limited" },
      { status: 429, headers: { "retry-after": String(limit.retryAfter) } },
    );
  }

  let body: { day?: unknown; emoji?: unknown; voter?: unknown; trip?: unknown };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "bad_json" }, { status: 400 });
  }

  const day = typeof body.day === "string" ? body.day : "";
  const voter = typeof body.voter === "string" ? body.voter : "";
  const tripId =
    typeof body.trip === "string" ? body.trip : "";
  // Voter ids are generated by the browser; cap the length so a hostile client
  // can't grow the store one enormous key at a time.
  if (!day || !voter || voter.length > 64) {
    return NextResponse.json({ error: "bad_request" }, { status: 400 });
  }
  if (!getTrip(tripId)) {
    return NextResponse.json({ error: "unknown_trip" }, { status: 400 });
  }

  try {
    const result = await vote(tripId, day, voter, body.emoji);
    return NextResponse.json(result, {
      headers: { "cache-control": "no-store" },
    });
  } catch {
    return NextResponse.json({ error: "unknown_reaction" }, { status: 400 });
  }
}
