// Generated by open-core/split/split.mjs: this feature is not included in this build.
const notIncluded = (): Response => new Response(null, { status: 404 });
export { notIncluded as GET, notIncluded as PUT };
