#!/usr/bin/env node
/**
 * Rasterise the mark into every bitmap that cannot take the SVG:
 * `docs/branding/fernscout-avatar-640.png`, and — B2124 — the iPhone app's
 * icon and launch screens under `ios/App/App/Assets.xcassets`.
 *
 * It exists because some slots cannot take an SVG. WhatsApp's business
 * profile is the one that forced it: it accepts JPEG and PNG only, and the
 * profile picture is the first thing a reader sees next to a message they did
 * not ask for, so it has to be the real mark rather than something redrawn to
 * fit the upload form.
 *
 * **The PNG is derived, and that is the whole risk.** BRAND.md's rule is that
 * the geometry lives in one place and the three files carrying copies of it
 * move together; a checked-in bitmap is a fourth copy that cannot be diffed
 * and will not complain when the mark changes underneath it. So it is
 * generated by this script and never by hand, and `npm run avatar` regenerates
 * it — run that whenever `fernscout-mark.svg` changes, in the same commit.
 *
 * **It carries its own copyright notice**, written in below as PNG text
 * chunks. The SVGs carry theirs as a comment in the file; a bitmap has
 * nowhere to put one but its metadata, and a copy that leaves the repository
 * takes whatever the file itself holds and nothing else. Regenerating without
 * writing them back would silently drop the only claim travelling with it —
 * which is why it happens here rather than by hand afterwards. B657.
 *
 * Flattened onto the plate's own navy rather than kept transparent: every
 * platform that wants a PNG avatar also crops it to a circle, and a
 * transparent corner would show that platform's ground instead of the mark's.
 * The SVG is not modified to do this — the rounded corners are still there,
 * they are simply navy on navy.
 */
import sharp from "sharp";
import fs from "node:fs";
import zlib from "node:zlib";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const source = path.join(root, "docs/branding/fernscout-mark.svg");
const target = path.join(root, "docs/branding/fernscout-avatar-640.png");

/** The plate colour in `fernscout-mark.svg`. Kept in step with it by the
 * assertion below rather than by hope. */
const NAVY = "#1e293b";
const SIZE = 640;
/** Fixed, not `new Date()`: the notice must not rewrite the file on a run
 * that changed no pixels. Bump it when the mark is next redrawn. */
const YEAR = 2026;

const svg = fs.readFileSync(source);
if (!svg.includes(NAVY)) {
  throw new Error(
    `${path.relative(root, source)} no longer contains ${NAVY}. The avatar is ` +
      `flattened onto that colour, so this script needs updating with the mark.`,
  );
}

/** The notice the file carries with it. The holder is read from
 * `site/config.json` rather than written here, for two reasons: no real name
 * belongs under `scripts/` (test/depersonalised.test.ts), and an instance
 * that regenerates this with its own mark should be stamping its own name on
 * it rather than somebody else's. Keep the wording in step with the SVG
 * comments and the BRAND ASSETS section of LICENSE. */
const { site } = JSON.parse(fs.readFileSync(path.join(root, "site/config.json"), "utf8"));
const holder = site?.credit?.name;
const NOTICE = {
  Copyright: holder ? `Copyright ${YEAR} ${holder}` : `Copyright ${YEAR} — see LICENSE`,
  ...(holder ? { Author: holder } : {}),
  Disclaimer:
    `The ${site?.name ?? "Fernscout"} wordmark and waymark are not licensed for use as the ` +
    "identity of another project or product. See TRADEMARK.md and the BRAND " +
    "ASSETS section of LICENSE.",
};

/** One PNG `tEXt` chunk: length, type, keyword\0text, CRC of type+data.
 * sharp cannot write these, and a 40-line dependency to add three strings
 * would be the wrong trade. */
function textChunk(keyword, text) {
  const data = Buffer.concat([Buffer.from(keyword, "latin1"), Buffer.from([0]), Buffer.from(text, "latin1")]);
  const type = Buffer.from("tEXt", "latin1");
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(zlib.crc32(Buffer.concat([type, data])));
  return Buffer.concat([len, type, data, crc]);
}

/** Write a PNG with the notice inserted before IEND, the last 12 bytes of
 * any valid PNG. */
function writeStamped(file, png, what) {
  const iend = png.length - 12;
  fs.writeFileSync(file, Buffer.concat([
    png.subarray(0, iend),
    ...Object.entries(NOTICE).map(([k, v]) => textChunk(k, v)),
    png.subarray(iend),
  ]));
  console.log(`${path.relative(root, file)} — ${what}, from ${path.basename(source)}, with notice`);
}

writeStamped(
  target,
  await sharp(svg, { density: 900 })
    .resize(SIZE, SIZE, { fit: "contain", background: NAVY })
    .flatten({ background: NAVY })
    .png({ compressionLevel: 9 })
    .toBuffer(),
  `${SIZE}x${SIZE}`,
);

/**
 * The iPhone app — B2124. Apple wants one 1024px icon with no transparency
 * (it rounds the corners itself), so the mark is flattened onto its own navy
 * exactly like the avatar. The launch screen is what shows for the instant
 * before the first page arrives: the mark alone, centred on the page's own
 * ground, cream in light and navy in dark, at the 2732px square Capacitor's
 * storyboard scales to fill. Both grounds are the tokens in
 * `app/globals.css` (`--color-cream-50`, `--color-navy-900`); the assertion
 * on NAVY above already ties this file to the mark's plate.
 */
const ios = path.join(root, "ios/App/App/Assets.xcassets");
const CREAM = "#fffaf0";
const ICON = 1024;
const SPLASH = 2732;
const MARK_ON_SPLASH = 512;

writeStamped(
  path.join(ios, "AppIcon.appiconset/AppIcon-512@2x.png"),
  await sharp(svg, { density: 1200 })
    .resize(ICON, ICON, { fit: "contain", background: NAVY })
    .flatten({ background: NAVY })
    .png({ compressionLevel: 9 })
    .toBuffer(),
  `${ICON}x${ICON} app icon`,
);

// The share extension's own copy of the mark, 44pt at 1x/2x/3x — B2183.
// It cannot read the app's asset catalog, so it carries one small image.
for (const scale of [1, 2, 3]) {
  const px = 44 * scale;
  writeStamped(
    path.join(root, "ios/App/ShareInbox/Assets.xcassets/Mark.imageset", `mark-${scale}x.png`),
    await sharp(svg, { density: 900 })
      .resize(px, px, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } })
      .png({ compressionLevel: 9 })
      .toBuffer(),
    `${px}x${px} share-sheet mark`,
  );
}

const markForSplash = await sharp(svg, { density: 900 })
  .resize(MARK_ON_SPLASH, MARK_ON_SPLASH, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } })
  .png()
  .toBuffer();
// One file per scale, the same pixels three times, because the launch
// storyboard is drawn by a restricted process that resolves only explicit
// 1x/2x/3x entries — a single unscaled entry compiles and then shows white.
for (const [stem, ground] of [["splash-light", CREAM], ["splash-dark", NAVY]]) {
  const png = await sharp({ create: { width: SPLASH, height: SPLASH, channels: 4, background: ground } })
    .composite([{ input: markForSplash, gravity: "centre" }])
    .flatten({ background: ground })
    .png({ compressionLevel: 9 })
    .toBuffer();
  for (const scale of [1, 2, 3]) {
    writeStamped(path.join(ios, "Splash.imageset", `${stem}-${scale}x.png`), png, `${SPLASH}x${SPLASH} launch screen on ${ground}, ${scale}x`);
  }
}
