#!/usr/bin/env node
/**
 * Rasterise the mark into the avatar PNG — `docs/branding/fernscout-avatar-640.png`.
 *
 * It exists because some slots cannot take an SVG. WhatsApp's business
 * profile is the one that forced it: it accepts JPEG and PNG only, and the
 * profile picture is the first thing a reader sees next to a message they did
 * not ask for, so it has to be the real mark rather than something redrawn to
 * fit the upload form.
 *
 * **The PNG is derived, and that is the whole risk.** BRAND.md's rule is that
 * the geometry lives in one place and the three files carrying copies of it
 * move together; a checked-in bitmap is a fourth copy that cannot be diffed
 * and will not complain when the mark changes underneath it. So it is
 * generated by this script and never by hand, and `npm run avatar` regenerates
 * it — run that whenever `fernscout-mark.svg` changes, in the same commit.
 *
 * Flattened onto the plate's own navy rather than kept transparent: every
 * platform that wants a PNG avatar also crops it to a circle, and a
 * transparent corner would show that platform's ground instead of the mark's.
 * The SVG is not modified to do this — the rounded corners are still there,
 * they are simply navy on navy.
 */
import sharp from "sharp";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const source = path.join(root, "docs/branding/fernscout-mark.svg");
const target = path.join(root, "docs/branding/fernscout-avatar-640.png");

/** The plate colour in `fernscout-mark.svg`. Kept in step with it by the
 * assertion below rather than by hope. */
const NAVY = "#1e293b";
const SIZE = 640;

const svg = fs.readFileSync(source);
if (!svg.includes(NAVY)) {
  throw new Error(
    `${path.relative(root, source)} no longer contains ${NAVY}. The avatar is ` +
      `flattened onto that colour, so this script needs updating with the mark.`,
  );
}

await sharp(svg, { density: 900 })
  .resize(SIZE, SIZE, { fit: "contain", background: NAVY })
  .flatten({ background: NAVY })
  .png({ compressionLevel: 9 })
  .toFile(target);

console.log(`${path.relative(root, target)} — ${SIZE}x${SIZE}, from ${path.basename(source)}`);
