#!/usr/bin/env node
/**
 * Rasterise the mark into the avatar PNG — `docs/branding/fernscout-avatar-640.png`.
 *
 * It exists because some slots cannot take an SVG. WhatsApp's business
 * profile is the one that forced it: it accepts JPEG and PNG only, and the
 * profile picture is the first thing a reader sees next to a message they did
 * not ask for, so it has to be the real mark rather than something redrawn to
 * fit the upload form.
 *
 * **The PNG is derived, and that is the whole risk.** BRAND.md's rule is that
 * the geometry lives in one place and the three files carrying copies of it
 * move together; a checked-in bitmap is a fourth copy that cannot be diffed
 * and will not complain when the mark changes underneath it. So it is
 * generated by this script and never by hand, and `npm run avatar` regenerates
 * it — run that whenever `fernscout-mark.svg` changes, in the same commit.
 *
 * **It carries its own copyright notice**, written in below as PNG text
 * chunks. The SVGs carry theirs as a comment in the file; a bitmap has
 * nowhere to put one but its metadata, and a copy that leaves the repository
 * takes whatever the file itself holds and nothing else. Regenerating without
 * writing them back would silently drop the only claim travelling with it —
 * which is why it happens here rather than by hand afterwards. B657.
 *
 * Flattened onto the plate's own navy rather than kept transparent: every
 * platform that wants a PNG avatar also crops it to a circle, and a
 * transparent corner would show that platform's ground instead of the mark's.
 * The SVG is not modified to do this — the rounded corners are still there,
 * they are simply navy on navy.
 */
import sharp from "sharp";
import fs from "node:fs";
import zlib from "node:zlib";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const source = path.join(root, "docs/branding/fernscout-mark.svg");
const target = path.join(root, "docs/branding/fernscout-avatar-640.png");

/** The plate colour in `fernscout-mark.svg`. Kept in step with it by the
 * assertion below rather than by hope. */
const NAVY = "#1e293b";
const SIZE = 640;
/** Fixed, not `new Date()`: the notice must not rewrite the file on a run
 * that changed no pixels. Bump it when the mark is next redrawn. */
const YEAR = 2026;

const svg = fs.readFileSync(source);
if (!svg.includes(NAVY)) {
  throw new Error(
    `${path.relative(root, source)} no longer contains ${NAVY}. The avatar is ` +
      `flattened onto that colour, so this script needs updating with the mark.`,
  );
}

/** The notice the file carries with it. The holder is read from
 * `site/config.json` rather than written here, for two reasons: no real name
 * belongs under `scripts/` (test/depersonalised.test.ts), and an instance
 * that regenerates this with its own mark should be stamping its own name on
 * it rather than somebody else's. Keep the wording in step with the SVG
 * comments and the BRAND ASSETS section of LICENSE. */
const { site } = JSON.parse(fs.readFileSync(path.join(root, "site/config.json"), "utf8"));
const holder = site?.credit?.name;
const NOTICE = {
  Copyright: holder ? `Copyright ${YEAR} ${holder}` : `Copyright ${YEAR} — see LICENSE`,
  ...(holder ? { Author: holder } : {}),
  Disclaimer:
    `The ${site?.name ?? "Fernscout"} wordmark and waymark are not licensed for use as the ` +
    "identity of another project or product. See TRADEMARK.md and the BRAND " +
    "ASSETS section of LICENSE.",
};

/** One PNG `tEXt` chunk: length, type, keyword\0text, CRC of type+data.
 * sharp cannot write these, and a 40-line dependency to add three strings
 * would be the wrong trade. */
function textChunk(keyword, text) {
  const data = Buffer.concat([Buffer.from(keyword, "latin1"), Buffer.from([0]), Buffer.from(text, "latin1")]);
  const type = Buffer.from("tEXt", "latin1");
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(zlib.crc32(Buffer.concat([type, data])));
  return Buffer.concat([len, type, data, crc]);
}

const png = await sharp(svg, { density: 900 })
  .resize(SIZE, SIZE, { fit: "contain", background: NAVY })
  .flatten({ background: NAVY })
  .png({ compressionLevel: 9 })
  .toBuffer();

// Insert before IEND, which is the last 12 bytes of any valid PNG.
const iend = png.length - 12;
fs.writeFileSync(target, Buffer.concat([
  png.subarray(0, iend),
  ...Object.entries(NOTICE).map(([k, v]) => textChunk(k, v)),
  png.subarray(iend),
]));

console.log(`${path.relative(root, target)} — ${SIZE}x${SIZE}, from ${path.basename(source)}, with notice`);
